/**
 * Downloads the self-hosted web fonts and regenerates src/styles/fonts.css.
 *
 * Run by hand, not as part of the build — the woff2 files and the generated
 * stylesheet are committed:
 *
 *   node scripts/fetch-fonts.mjs
 *
 * VARIANTS below is deliberately narrow. It lists only the family / weight /
 * style combinations the site actually renders, measured from computed styles
 * across every page. Add to it only after confirming something on screen needs
 * it, otherwise visitors pay for fonts nobody sees.
 *
 * Cinzel, Cormorant Garamond and Josefin Sans are all SIL Open Font License
 * 1.1, which permits self-hosting. See public/fonts/OFL.txt.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'public/fonts');

/** The Google Fonts CSS2 query for exactly what the site uses. */
const FAMILIES = [
  'Cinzel:wght@400',
  'Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400',
  'Josefin+Sans:wght@400;500',
];

/** English-language site: the other subsets Google ships are dead weight. */
const SUBSETS = new Set(['latin', 'latin-ext']);

/** A modern UA is what makes the API answer with woff2 rather than ttf. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36';

const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f}`).join(
  '&',
)}&display=swap`;

const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts answered ${r.status}`);
  return r.text();
});

// Each @font-face in the response is preceded by a /* subset */ comment.
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]+)\}/g)]
  .map(([, subset, body]) => {
    const get = (prop) => (body.match(new RegExp(`${prop}:\\s*([^;]+);`)) || [])[1]?.trim();
    return {
      subset,
      family: get('font-family').replace(/'/g, ''),
      style: get('font-style'),
      weight: get('font-weight'),
      src: get('src').match(/url\(([^)]+)\)/)[1],
      unicodeRange: get('unicode-range'),
    };
  })
  .filter((b) => SUBSETS.has(b.subset));

fs.mkdirSync(outDir, { recursive: true });

const faces = [];
for (const b of blocks) {
  // The version lives in the gstatic path. Keeping it in the filename is what
  // makes the immutable cache header in netlify.toml safe.
  const version = b.src.match(/\/s\/[^/]+\/(v\d+)\//)?.[1] ?? 'v0';
  const name = `${slug(b.family)}-${version}-${b.weight}${
    b.style === 'italic' ? 'i' : ''
  }-${b.subset}.woff2`;

  const bytes = Buffer.from(await fetch(b.src).then((r) => r.arrayBuffer()));
  fs.writeFileSync(path.join(outDir, name), bytes);
  console.log(`  ${name.padEnd(44)} ${(bytes.length / 1024).toFixed(1)} kB`);

  faces.push({ ...b, file: `/fonts/${name}` });
}

const order = { Cinzel: 0, 'Cormorant Garamond': 1, 'Josefin Sans': 2 };
faces.sort(
  (a, b) =>
    order[a.family] - order[b.family] ||
    a.weight - b.weight ||
    a.style.localeCompare(b.style) ||
    a.subset.localeCompare(b.subset),
);

const sheet = `/* Self-hosted web fonts — generated by scripts/fetch-fonts.mjs, do not edit.
 *
 * Only the seven family/weight/style combinations the site actually renders
 * are here; Google's stylesheet asked the browser for fourteen. Each is split
 * into the latin and latin-ext subsets, so the accented block is fetched only
 * when a page needs it.
 *
 * font-display: swap throughout — text paints straight away in the fallback
 * and reflows when the webfont arrives, rather than sitting invisible.
 */

${faces
  .map(
    (f) => `/* ${f.subset} */
@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('${f.file}') format('woff2');
  unicode-range: ${f.unicodeRange};
}`,
  )
  .join('\n\n')}
`;

fs.writeFileSync(path.join(root, 'src/styles/fonts.css'), sheet);
console.log(`\n  src/styles/fonts.css — ${faces.length} @font-face rules`);

const preload = faces.filter(
  (f) =>
    f.subset === 'latin' &&
    f.style === 'normal' &&
    ((f.family === 'Cormorant Garamond' && f.weight === '400') ||
      (f.family === 'Josefin Sans' && f.weight === '400')),
);
console.log('\n  index.html should preload:');
for (const f of preload) console.log(`    ${f.file}`);
